name = "NLS_Solver"
uuid = "4f18ef6b-35d7-46eb-a297-26b97f1ff488"
authors = ["Picaud Vincent <picaud.vincent@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ReadOnlyArrays = "988b38a3-91fc-5605-94a2-ee2116b3bd83"

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
