name = "NLS_Solver"
uuid = "4f18ef6b-35d7-46eb-a297-26b97f1ff488"
authors = ["Picaud Vincent <picaud.vincent@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
